name: 'Setup GNU coreutils'
description: 'Setup GNU coreutils in the workflow.'
branding:
  icon: 'package'  
  color: 'green'
runs:
  using: "composite"
  steps:
    - name: "Install dependencies"
      run: |
        echo "::group::Install dependencies"
        sudo apt-get -y install autoconf automake autopoint gperf xz-utils
        echo "::endgroup::"
      shell: bash
    - name: "Setup GNU coreutils"
      run: ${{ github.action_path }}/setup.sh
      shell: bash