on: [push]

jobs:
  test-coreutils:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: ./
      - name: Native utils diagnostics
        run: |
          if [ "$(uptime --version | grep -c "GNU coreutils")" == 1 ]
          then
            exit 0
          else
            exit 1
          fi